# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    # This environment tests that scikit-learn can be built against
    # versions of numpy, scipy with ATLAS that comes with Ubuntu Trusty 14.04
    # i.e. numpy 1.8.2 and scipy 0.13.3
    - env: DISTRIB="ubuntu" PYTHON_VERSION="2.7" CYTHON_VERSION="0.23.5"
           COVERAGE=true
      if: type != cron
      addons:
        apt:
          packages:
            # these only required by the DISTRIB="ubuntu" builds:
            - python-scipy
            - libatlas3-base
            - libatlas-dev
    # Python 3.4 build
    - env: DISTRIB="conda" PYTHON_VERSION="3.4" INSTALL_MKL="false"
           NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1" CYTHON_VERSION="0.25.2"
           PILLOW_VERSION="4.0.0" COVERAGE=true
      if: type != cron
    # This environment tests the newest supported Anaconda release (5.0.0)
    # It also runs tests requiring Pandas and PyAMG
    - env: DISTRIB="conda" PYTHON_VERSION="3.6.2" INSTALL_MKL="true"
           NUMPY_VERSION="1.14.2" SCIPY_VERSION="1.0.0" PANDAS_VERSION="0.20.3"
           CYTHON_VERSION="0.26.1" PYAMG_VERSION="3.3.2" PILLOW_VERSION="4.3.0"
           COVERAGE=true
           CHECK_PYTEST_SOFT_DEPENDENCY="true" TEST_DOCSTRINGS="true"
      if: type != cron
    # flake8 linting on diff wrt common ancestor with upstream/master
    - env: RUN_FLAKE8="true" SKIP_TESTS="true"
           DISTRIB="conda" PYTHON_VERSION="3.5" INSTALL_MKL="true"
           NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1"
           CYTHON_VERSION="0.26.1"
      if: type != cron
    # This environment tests scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    -  python: 3.6
       env: DISTRIB="scipy-dev-wheels"
       if: type = cron

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
